spring:
  profiles:
    active: local
  cache:
    jcache:
      config: ehcache.xml
  main:
    allow-bean-definition-overriding: true

server:
  port: 7777

camel:
  component:
    servlet:
      mapping:
        context-path: /*

  springboot:
    main-run-controller: true
    name: Application
    stream-caching-enabled: true
    startup-summary-level: verbose
    routes-include-pattern: classpath:camel/*.xml

management:
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true

mambu:
  host: modusbox.sandbox.mambu.com
  username: shashi
  password: Modusbox@123

error:
  default:
    code: PORTX_OBA_ERROR
    message: A generic error happened in PortX OBA Proc API
  authentication:
    code: PORTX_OBA_AUTHENTICATION
    message: Authentication error
  createresource:
    code: PORTX_OBA_CREATERESOURCE
    message: Unable to create a new resource
  findresource:
    code: PORTX_OBA_FINDRESOURCE
    message: Unable to find an existing resource
  updateresource:
    code: PORTX_OBA_UPDATERESOURCE
    message: Unable to update a resource
  removesource:
    code: PORTX_OBA_REMOVERESOURCE
    message: Unable to remove a resource
