version: '3'

services:
  db:
    image: postgres:13-alpine
    container_name: pg13
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=portxoba
      - POSTGRES_PASSWORD=portxoba
      - POSTGRES_DB=portxoba