openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: /mambu-portx-cbs-connector/1.0
info:
  title:  Bank Account Management
  description: Bank Account Management
  contact:
    email: betiana.darderes@modusbox.com
  version: 1.0.0
security:
  - jwt: []
  - openIdConnect: []
tags:
  - name: Accounts
    description: Bank Account Management
paths:
  /accounts:
    post:
      tags:
        - Accounts
      summary: Opens an account
      operationId: openAccount
      parameters:
        - $ref: "#/components/parameters/idempotencyId"
        - $ref: "#/components/parameters/bankId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountOpeningRequest'
        required: true
      responses:
        '202':
          description: Account information was received and will be processed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountRequestAcknowledgement'
        '400':
          description: Bad Request. The account could not be processed due to format errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /accounts/{accountId}:
    get:
      tags:
        - Accounts
      summary: Retrieves an account
      operationId: findAccount
      parameters:
        - $ref: "#/components/parameters/accountId"
        - $ref: "#/components/parameters/bankId"
      responses:
        '200':
          description: Matching account was found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Bad Request. Account Id could not be processed due to format errors.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: No matching accounts have found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /banks:
    get:
      tags:
        - Banks
      summary: Retrieves banks
      operationId: findBanks
      responses:
        '200':
          description: Banks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BanksJson400'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /branches:
    get:
      tags:
        - Branches
      summary: Retrieves branches
      operationId: findBranches
      responses:
        '200':
          description: Branches
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BranchesJson400'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code.
        message:
          type: string
          description: Error message text.
        payload:
          type: object
          description: Error payload as json object.

    AccountId:
      type: string
      minLength: 1
      maxLength: 17
    PartyId:
      type: string
      minLength: 1
      maxLength: 17
    BranchId:
      type: string
      minLength: 1
      maxLength: 17
    CurrencyCode:
      type: string
      minLength: 3
      maxLength: 3
    AmountInCents:
      description: |
        Max amount: 999999999999
      type: integer
      format: int64
      minimum: 0
      maximum: 9999999999
    AccountType:
      type: string
      enum:
        - CASH
        - CPFO
        - CPFS
        - SRSA
    AccountStatus:
      type: string
      enum:
        - ENAB
        - DISA
        - DELE
        - FORM
    AccountOpeningRequest:
      type: object
      properties:
        branchId:
          $ref: '#/components/schemas/BranchId'
        partyId:
          $ref: '#/components/schemas/PartyId'
        type:
          $ref: '#/components/schemas/AccountType'
        name:
          type: string
          minLength: 1
          maxLength: 17
        currency:
          $ref: '#/components/schemas/CurrencyCode'
        amount:
          $ref: '#/components/schemas/AmountInCents'
    AccountRequestAcknowledgement:
      type: object
      properties:
        accountId:
          $ref: '#/components/schemas/AccountId'
        branchId:
          $ref: '#/components/schemas/BranchId'
        partyId:
          $ref: '#/components/schemas/PartyId'
        type:
          $ref: '#/components/schemas/AccountType'
        name:
          type: string
          minLength: 1
          maxLength: 17
        currency:
          $ref: '#/components/schemas/CurrencyCode'
        amount:
          $ref: '#/components/schemas/AmountInCents'
        status:
          $ref: '#/components/schemas/AccountStatus'
    BanksJson400:
      required:
        - banks
      properties:
        banks:
          type: array
          items:
            $ref: '#/components/schemas/BankJson400'
    BranchesJson400:
      required:
        - branches
      properties:
        branches:
          type: array
          items:
            $ref: '#/components/schemas/BranchJson400'
    BranchJson400:
      type: object
      properties:
        encodedKey:
          type: string
    BankJson400:
      required:
        - bank_routings
        - website
        - full_name
        - logo
        - id
        - short_name
      properties:
        id:
          type: string
          example: gh.29.uk
        short_name:
          type: string
          example: 'short_name'
        full_name:
          type: string
          example: full_name
        logo:
          type: string
          example: logo
        website:
          type: string
          example: www.openbankproject.com
        bank_routings:
          type: array
          items:
            $ref: '#/components/schemas/BankRoutingJsonV121'
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/BankAttributeBankResponseJsonV400'
    BankRoutingJsonV121:
      required:
        - scheme
        - address
      properties:
        scheme:
          type: string
          example: Bank_ID
        address:
          type: string
          example: gh.29.uk
    BankAttributeBankResponseJsonV400:
      required:
        - name
        - value
      properties:
        name:
          type: string
          example: ACCOUNT_MANAGEMENT_FEE
        value:
          type: string
          example: '5987953'
    Account:
      type: object
      properties:
        accountId:
          $ref: '#/components/schemas/AccountId'
        branchId:
          $ref: '#/components/schemas/BranchId'
        partyId:
          $ref: '#/components/schemas/PartyId'
        type:
          $ref: '#/components/schemas/AccountType'
        name:
          type: string
          minLength: 1
          maxLength: 17
        currency:
          $ref: '#/components/schemas/CurrencyCode'
        amount:
          $ref: '#/components/schemas/AmountInCents'
        status:
          $ref: '#/components/schemas/AccountStatus'
  parameters:
    idempotencyId:
      name: "idempotencyId"
      in: "header"
      description: "Idempotency identifier used by the client when making repeated calls"
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 17
    bankId:
      name: "bankId"
      in: "header"
      description: "Bank Identification"
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 17
    accountId:
      name: "accountId"
      in: path
      description: "Account Identification"
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/AccountId'