name: Build and publish to Maven repo and ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'Dockerfile'
      - 'Makefile'

jobs:
  push-to-maven-repo:
    env:
      REGISTRY: 854173534877.dkr.ecr.us-west-2.amazonaws.com
    name: Push to Maven repo
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: 18

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

#      - name: Configure main account AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.MAIN_AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.MAIN_AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-west-2
#
#       - name: Get mambu build settings.xml from s3
#         run: aws s3 cp s3://portx-fresno-ci/portx-build-settings.xml settings.xml

      - name: Push to Maven repo
        run: |
          git config --global user.email "ci@modusbox.com"
          git config --global user.name "ci"
          mvn -B -s settings.xml -DignoreSnapshots=true -Dusername=$GITHUB_ACTOR -Dpassword=${{ secrets.GITHUB_TOKEN }} release:prepare release:perform

  build-image-push-ecr:
    needs: push-to-maven-repo
    env:
      REGISTRY: 854173534877.dkr.ecr.us-west-2.amazonaws.com
    name: Build docker Image and Push to ECR
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: |
          git fetch --tags
          tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $tag -b latest

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Configure main account AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MAIN_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MAIN_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Log in to ECR
        run: aws ecr get-login-password | docker login --password-stdin --username AWS $REGISTRY

      - name: make status
        run: make status

      - name: make pull
        run: make pull

      - name: make full_build
        run: make full_build

      - name: make tag
        run: make tag

      - name: make push
        run: make push