name: build
on:
  push:
    branches:
      - develop
jobs:
  package-gbp-deploy-dr-push:
    env:
      REGISTRY: 823667448392.dkr.ecr.us-east-1.amazonaws.com
      APP_NAME: vnext/mambu-portx-cbs-connector
    name: Build API package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Maven Caching
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{"id":"portx-repository-snapshots", "url": "https://portx.jfrog.io/portx/portx-snapshots","releases":{"enabled":false},"snapshots":{"enabled":true}},{"id": "portx-repository-releases", "url": "https://portx.jfrog.io/portx/portx-releases","releases":{"enabled":true},"snapshots":{"enabled":false}}]'
          servers: |
            [{"id": "portx-repository-snapshots", "username": "deployer", "password": "${{ secrets.PORTX_SNAPSHOTS_PASSWORD }}"},{"id": "portx-repository-releases", "username": "deployer", "password": "${{ secrets.PORTX_RELEASES_PASSWORD }}"}]
      - name: Publish to Github packages
        run: mvn -U deploy -e
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          MAVEN_OPTS: --add-opens=java.base/java.util=ALL-UNNAMED
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Log in to ECR
        run: aws ecr get-login-password | docker login --password-stdin --username AWS $REGISTRY
      - name: Build and Push
        run: |
          docker build -t $REGISTRY/$APP_NAME -f Dockerfile .
          docker tag $REGISTRY/$APP_NAME $REGISTRY/$APP_NAME:dev-${{ github.sha }}-latest
          docker push $REGISTRY/$APP_NAME:dev-${{ github.sha }}-latest
